---
title: "Multiple Choice Quiz Example"
format:
  revealjs:
    quiz: 
      checkKey: 'c'
      resetKey: 'q'
      shuffleKey: 't'
      allowNumberKeys: true
      disableOnCheck: false
      shuffleOptions: true
revealjs-plugins:
  - quiz
---

## What is the capital of France? {.quiz-question}

- London
- [Paris]{.correct}
- Berlin
- Madrid

::: footer
Click on one of the options then click the check button. If you got it wrong click reset and try again.
:::


## What is the capital of the USA? {.quiz-question}

- Paris
- Berlin
- Madrid
- [Washington, D.C.]{.correct}

::: footer
Alternatively, you can select each option using your number keypad. For example, click "2" to select the second option. 
:::



## What is the capital of Spain? {.quiz-question}

- Paris
- Berlin
- [Madrid]{.correct}

::: footer
You can use the "c" key to check your answer, the "q" key to reset the question, and the "t" key to shuffle the question slides.
:::

## What is the capital of Germany? {.quiz-question}

- Paris
- [Berlin]{.correct}
- Madrid
- London

::: footer
Keyboard shortcuts can be changed in the YAML header of your Quarto file. See [README.md](README.md) for more info.
:::

